#!/usr/bin/env bash

set -e

my_dir="$(dirname "$0")"

source "$my_dir/scripts/pretty_wrapper_functions.sh"

TOTAL_START_TIME=$(date +%s.%N)

run_and_log "mix deps.get"
run_and_log "mix clean"
run_and_log "mix compile --warnings-as-errors"
run_and_log "mix test"
run_and_log "mix format --check-formatted"
run_and_log "mix credo --strict"

TOTAL_END_TIME=$(date +%s.%N)
TOTAL_DURATION=$(calculate_duration "$TOTAL_START_TIME" "$TOTAL_END_TIME")

echo_success "$(printf '%.0s═' {1..60})"
echo_success "✅ Build completed successfully in ${TOTAL_DURATION}"
echo_success "$(printf '%.0s═' {1..60})"
